---
title: 예외 처리
date: 2024-01-02 15:33
categories:
  - Java
  - Java문법
tags:
  - Java
  - Java문법
image: 
path:
---
#Java 

## 예외 처리
+ [[Throwable]]을 최상위 클래스로 가진다.
+ 실행 중 발생하는 [[🟠 Project/Java API/java.lang/Throwable/Exception]]에 대해 핸들링을 해 주는 것.
+ [[Error]]는 처리하지 않는다.
### 예외 Class 계층 구조
- **Checked Exception** : 예외처리를 해야 하는 Class
- **Unchecked Exception** : 예외처리를 해주지 않아도 되는 Class

![[error.png]]
### 1. Throws
+ 메소드 선언 시 throws ExceptionName문을 추가하여 호출한 상위 메소드에게 처리를 위임
```java
public void checkEnoughMoney(int price, int money) throws Exception{}
```

### 2. try-catch-finally
+ 발생한 예외 타입과 일치하는 catch블록이 없으면 강제 종료된다.
+ catch 블록 내에서 ```System.exit(0)```을 호출하면 프로그램을 종료할 수 있다.
```java
try{
	예외가 발생할 가능성이 있는 실행문(try 블록)
}
catch(처리할 예외 타입 선언){
	예외 처리문(catch 블록)
}
finally{ // 생략 가능
	예외 발생 여부와 상관없이 무조건 실행되는 문장(finally 블록)
}
```

### 3. try-with-resource
- finally에서 처리했던 close를 try문에서 자동으로 close처리한다.
- JDK 7부터 지원
```java
try(BufferedReader br = new BufferedReader(new FileReader("C/data/text.txt"))){
}
catch{
}
```

### Exception과 overriding
- Overriding시 throws하는 Exception의 개수와 상관없이 같거나 더 구체적인 범위로만 overriding이 가능하다.

```java
public class Parent{
			public void method() throws IOException{
			}
	}
	
	public class Child extends Parent{
		@override
		public void method() throws EOFException{
		}
	}
```

## 사용자 예외
+ 직접 예외를 만들 수 있다. 이때에는 Exception을 꼭 상속받아야 한다.

```java
class OurBadException extends Exception {
	public OurBadException() {
		super("위험한 행동을 하면 예외처리를 꼭 해야합니다!");
	}
}

```

## Chained Exception: 연결된 예외
+ 예외는 다른 예외를 유발할 수 있다.
+ 예외 A가 예외 B를 발생시켰다면, 예외 A는 B의 원인 예외이다.
+ 원인 예외를 새로운 예외에 등록한 후 다시 새로운 예외를 발생시키는데, 이를 예외 연결이라고 한다.

### 예외를 연결하는 이유?
1. 어떤 특정한 예외 상황을 만드는 원인이 되는 예외가 여러 가지일 경우, 하나의 큰 분류의 예외로 묶어서 다루기 위함이다.
2. checked exception을 unchecked exception으로 포장(wrapping)하는데 유용하게 사용되기도 한다.
3. 원인에 대한 tracking이 편하다.

### 원인 예외 메서드
+ `initCause` : 지정한 예외를 원인 예외로 등록하는 메소드
+ `getCause` : 원인 예외를 반환하는 메소드

```java
// 연결된 예외 
public class main {

    public static void main(String[] args) {
        try {
            // 예외 생성
            NumberFormatException ex = new NumberFormatException("가짜 예외이유");

            // 원인 예외 설정(지정한 예외를 원인 예외로 등록) chaining
            ex.initCause(new NullPointerException("진짜 예외이유"));

            throw ex;
        } catch (NumberFormatException ex) {
            // 예외 로그 출력
            ex.printStackTrace();
            // 예외 원인 조회 후 출력
            ex.getCause().printStackTrace();
        }

        // wrapping
        throw new RuntimeException(new Exception("이것이 진짜 예외 이유 입니다."));
    }
}

Caused by: java.lang.NullPointerException: 진짜 예외이유
```

## 실질적 예외 처리 방법
실질적으로 처리하는 방법은 **예외 복구, 예외 처리 회피, 예외 전환** 세 가지 경우가 있다.

### 예외 복구
+ 자주 사용되지는 않는 방식이다.

```java
public String getDataFromAnotherServer(String dataPath) {
		try {
				return anotherServerClient.getData(dataPath).toString();
		} catch (GetDataException e) {
				return defaultData;
		}
}
```

### 예외 처리 회피
+ 더 높은 단계의 메소드에서 처리하기 위해 내보내는 경우가 있다.

```java
public void someMethod() throws Exception { ... }

public void someIrresponsibleMethod() throws Exception {
		this.someMethod();
}
```

### 예외 전환하기
+ 회피와 비슷하지만, 조금 더 적절한 예외를 던져주는 경우로, 제일 많이 사용한다.

```java
public void someMethod() throws IOException { ... }

public void someResponsibleMethod() throws MoreSpecificException {
		try {
			this.someMethod();
		} catch (IOException e) {
			throw new MoreSpecificException(e.getMessage());
		}
}
```